help:
	@echo 'Targets:'
	@grep -h -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2}'


unexport VIRTUAL_ENV

help::
	echo "Targets:"
	echo "  local"
	echo "  check"
	echo "  clean"
	echo "  build"

local::  ## Setup up local development
	poetry lock --no-update
	poetry install

local::
ifneq (,$(wildcard ./.git))
	pre-commit install
endif

check::  ## Check software
	poetry run mypy {{project}}

check::
	poetry run ruff check {{project}}

check::
	poetry run pytest tests

update::  ## Update library dependencies
	poetry update

build:: check

clean::  ## Clean temporary files
