unexport VIRTUAL_ENV

help::
	echo "Targets:"
	echo "  local"
	echo "  check"
	echo "  clean"
	echo "  build"

local::
	poetry lock --no-update
	poetry install

local::
ifeq (,$(wildcard ./git))
	pre-commit install
endif

check::
	poetry run mypy {{project}}

check::
	poetry run ruff check {{project}}

check::
	poetry run pytest tests

update::
	poetry update

build::
